name: backend
description: A starting point for a scalable backend server for CreacionesBaby using Dart.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  supabase: ^1.11.0 # Pure Dart Supabase client
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
